// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1) {
  return window['go']['app']['App']['AcceptTransfer'](arg1);
}

export function ConfirmRegistration() {
  return window['go']['app']['App']['ConfirmRegistration']();
}

export function CreatePassword(arg1) {
  return window['go']['app']['App']['CreatePassword'](arg1);
}

export function DeleteFiles(arg1) {
  return window['go']['app']['App']['DeleteFiles'](arg1);
}

export function DeleteFolders(arg1) {
  return window['go']['app']['App']['DeleteFolders'](arg1);
}

export function ExportFiles(arg1) {
  return window['go']['app']['App']['ExportFiles'](arg1);
}

export function ExportZipFolders(arg1, arg2) {
  return window['go']['app']['App']['ExportZipFolders'](arg1, arg2);
}

export function GetFilesInFolder(arg1) {
  return window['go']['app']['App']['GetFilesInFolder'](arg1);
}

export function GetLocalIPs() {
  return window['go']['app']['App']['GetLocalIPs']();
}

export function GetServerPIN() {
  return window['go']['app']['App']['GetServerPIN']();
}

export function GetStoredFolders() {
  return window['go']['app']['App']['GetStoredFolders']();
}

export function GetWiFiNetworkName() {
  return window['go']['app']['App']['GetWiFiNetworkName']();
}

export function IsFirstTimeSetup() {
  return window['go']['app']['App']['IsFirstTimeSetup']();
}

export function IsServerRunning() {
  return window['go']['app']['App']['IsServerRunning']();
}

export function LockApp() {
  return window['go']['app']['App']['LockApp']();
}

export function RejectRegistration() {
  return window['go']['app']['App']['RejectRegistration']();
}

export function RejectTransfer(arg1) {
  return window['go']['app']['App']['RejectTransfer'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartServer(arg1) {
  return window['go']['app']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['app']['App']['StopServer']();
}

export function StopTransfer(arg1) {
  return window['go']['app']['App']['StopTransfer'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['app']['App']['VerifyPassword'](arg1);
}
