// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filestore} from '../models';
import {context} from '../models';

export function AcceptTransfer(arg1:string):Promise<void>;

export function ConfirmRegistration():Promise<void>;

export function CreatePassword(arg1:string):Promise<void>;

export function DeleteFiles(arg1:Array<number>):Promise<void>;

export function DeleteFolders(arg1:Array<number>):Promise<void>;

export function ExportFiles(arg1:Array<number>):Promise<Array<string>>;

export function ExportZipFolders(arg1:Array<number>,arg2:Array<number>):Promise<Array<string>>;

export function GetFilesInFolder(arg1:number):Promise<filestore.FilesInFolderResponse>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetServerPIN():Promise<string>;

export function GetStoredFolders():Promise<Array<filestore.FolderInfo>>;

export function GetWiFiNetworkName():Promise<string>;

export function IsFirstTimeSetup():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function LockApp():Promise<void>;

export function RejectRegistration():Promise<void>;

export function RejectTransfer(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer():Promise<void>;

export function StopTransfer(arg1:string):Promise<void>;

export function VerifyPassword(arg1:string):Promise<void>;
